# Generated by Django 5.1 on 2024-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_moodtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='vlue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
